on:
  push:
    branches:
    - main
jobs:
  build:
    name: Build Document
    runs-on: ubuntu-latest
    steps:
    - uses: WtfJoke/setup-tectonic@v3.0.2
      with:
        # The GITHUB_TOKEN secret. Used for querying tectonic releases
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - run: make
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: final-report
        path: css2_final_report.pdf

          
